
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action SaveConfigAction;
	private global::Gtk.Action FileAction1;
	private global::Gtk.Action SaveConfigAction1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar2;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.HBox hbox3;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Label label6;
	private global::Gtk.Entry entry1;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.Label label7;
	private global::Gtk.Entry entry2;
	private global::Gtk.HSeparator hseparator3;
	private global::Gtk.Label label8;
	private global::Gtk.Entry entry3;
	private global::Gtk.HSeparator hseparator4;
	private global::Gtk.Label label9;
	private global::Gtk.Entry entry4;
	private global::Gtk.HSeparator hseparator5;
	private global::Gtk.Label label10;
	private global::Gtk.Entry entry5;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.SaveConfigAction = new global::Gtk.Action ("SaveConfigAction", global::Mono.Unix.Catalog.GetString ("Save Config"), null, null);
		this.SaveConfigAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Config");
		w1.Add (this.SaveConfigAction, null);
		this.FileAction1 = new global::Gtk.Action ("FileAction1", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction1, null);
		this.SaveConfigAction1 = new global::Gtk.Action ("SaveConfigAction1", global::Mono.Unix.Catalog.GetString ("Save Config"), null, null);
		this.SaveConfigAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Config");
		w1.Add (this.SaveConfigAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction1' action='FileAction1'><menuitem name='SaveConfigAction1' action='SaveConfigAction1'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("00:00:00");
		this.vbox1.Add (this.label4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label4]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		w3.Padding = ((uint)(2));
		// Container child vbox1.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("ETF: 00:00:00");
		this.vbox1.Add (this.label5);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label5]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		w4.Padding = ((uint)(2));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		this.hbox3.BorderWidth = ((uint)(15));
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.WidthRequest = 210;
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Working hours");
		this.label6.Justify = ((global::Gtk.Justification)(2));
		this.vbox3.Add (this.label6);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label6]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.vbox3.Add (this.entry1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entry1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox3.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator1]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		w7.Padding = ((uint)(2));
		// Container child vbox3.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Lunch Time (minutes)");
		this.vbox3.Add (this.label7);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label7]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.vbox3.Add (this.entry2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entry2]));
		w9.Position = 4;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.vbox3.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator3]));
		w10.Position = 5;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Coffee 1 (minutes)");
		this.vbox3.Add (this.label8);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label8]));
		w11.Position = 6;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.vbox3.Add (this.entry3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entry3]));
		w12.Position = 7;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hseparator4 = new global::Gtk.HSeparator ();
		this.hseparator4.Name = "hseparator4";
		this.vbox3.Add (this.hseparator4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator4]));
		w13.Position = 8;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Coffee 2 (minutes)");
		this.vbox3.Add (this.label9);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label9]));
		w14.Position = 9;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '●';
		this.vbox3.Add (this.entry4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entry4]));
		w15.Position = 10;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hseparator5 = new global::Gtk.HSeparator ();
		this.hseparator5.Name = "hseparator5";
		this.vbox3.Add (this.hseparator5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator5]));
		w16.Position = 11;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Startup time (minutes)");
		this.vbox3.Add (this.label10);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label10]));
		w17.Position = 12;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entry5 = new global::Gtk.Entry ();
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '●';
		this.vbox3.Add (this.entry5);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entry5]));
		w18.Position = 13;
		w18.Expand = false;
		w18.Fill = false;
		this.hbox3.Add (this.vbox3);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox3]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w20.Position = 3;
		w20.Expand = false;
		w20.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 441;
		this.DefaultHeight = 431;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
